export const addNoteCommands = ["dodaj notatkę", "chciałbym dodać notatkę", "dodasz notatke", "nowa notatka"]
export const addTitleCommands = ['dodaj tytuł', 'wstaw tytuł', 'tytuł', 'tytuł to będzie','a tytuł to będzie', 'a tytuł  niech będzie']
export const addContentCommands = ['dodaj opis', 'dodaj treść', 'a opis to będzie', 'opis to będzie']
export const deleteNoteCommands = ["usuń notatkę", "chciałbym usunąć notatkę", "usuniesz notatkę", "usuń mi notatkę"]
export const deleteTitleCommands = ['notatkę o tytule', 'tytuł to']
